### ISSUE TITLE
User cannot connect to any account to access files

### ISSUE THREAD

**Issue by WernherVonDown** [filestack/filestack-react#109]
Steps to reproduce the bug with Google Drive, for example:
Click on "Connect Google Drive" button
Choose a google account
Give permission for filestack to read my drive
Expected result: filestack gets permission to access my google drive files, they are visible
Actual result: user gets an error "Api key not found. Be sure that you are setting it with filepicker.setKey(). If you need an api key or forgot yours, head on over to https://developers.filepicker.io" https://skr.sh/s6IHrvy5Ccj url: https://dialog.filestackapi.com/dialog/open/?auth=true#/GoogleDrive/
Additional info:
My API key is fine and working - it works in another package 
The same result happens when I attempt to connect to OneDrive or facebook
Dropbox and Cloud Drive show an error right inside of the plugin https://skr.sh/s6IrJOall10

**Comment by phlare** [comment]
what was the resolution here?   I get the same issue so i updated my filestack-react version, and now these integrations work locally, but on production just give me "This folder is empty" and never even try to do an Oauth flow
