### ISSUE TITLE
Bump and publish latest version of the module to npmjs.com

### ISSUE THREAD

**Issue by geoffrey** [filestack/filestack-react#11]
I would love to be able to use https://github.com/filestack/react-filestack/pull/7
The latest is `0.6.6` right now but does not contain that fix.

Thanks for that module!

**Comment by samuxyz** [comment]
Hey @geoffrey we are gonna do it asap. Thanks for the patience

**Comment by samuxyz** [comment]
@geoffrey was published yesterday, i close the issue.
