### ISSUE TITLE
Add onClose prop to properly handle the picker being closed

### ISSUE THREAD

**Issue by highri5e** [filestack/filestack-react#114]
Since we're now handling the showing of the PickerOverlay ourselves, it would be good to have an onClose prop for PickerOverlay (just like onSuccess, onError) so we can handle the event of the picker being closed from within it's UI.

This is so we can update our state when the user closes the PickerOverlay with the x in the top right corner or hit ESC.

**Comment by josephrace** [comment]
In case it still helps - the filestack-js picker options (see https://filestack.github.io/filestack-js/interfaces/pickeroptions.html) are exposed through the `pickerOptions` prop and there's an `onClose` method there e.g.

```
<PickerOverlay
  apikey={YOUR_API_KEY}
  pickerOptions={{
    onClose: () => {
      // update your state
    }
  }}
/>
```

**Comment by highri5e** [comment]
Great thanks @josephrace!!!

**Comment by MagdielPm** [comment]
Amazing, it works!! Thanks @josephrace 🚀
