### ISSUE TITLE
proptypes error in 0.9.1

### ISSUE THREAD

**Issue by phlare** [filestack/filestack-react#18]
hi!   loving this package so far, and I just updated to take advantage of the custom rendering mode, but am now getting a warning in my console about using PropTypes directly:

```Warning: Failed prop type: Calling PropTypes validators directly is not supported by the `prop-types` package. Use PropTypes.checkPropTypes() to call them. Read more at http://fb.me/use-check-prop-types```

I also see this same error message in the `react-filestack.js` minified file

any help you can provide would be great, I do know that i'm using a slightly older react version than is specified in the devDependencies, but i'm using a version greater than that set in the peerDependencies.  not sure if there's anything else i can do on my end though.

**Comment by rockia** [comment]
I have the same issue with current version 0.9.1

**Comment by advance512** [comment]
Can this please be fixed? It is highly annoying and super easy to remedy.

**Comment by ZeroCho** [comment]
@advance512 Could you tell me how this can be fixed?

**Comment by samuxyz** [comment]
@advance512 @rockia @phlare I updated the devDependencies versions of react and prop-types, this solved the problem in my test component importing react-filestack. Let me know if it doesn't work. For now I close the issue.

@ZeroCho Thanks for being here to support.

**Comment by advance512** [comment]
Fixed. Thanks, @samuxyz.
