### ISSUE TITLE
Minification Issue 

### ISSUE THREAD

**Issue by muaaz-vf** [filestack/filestack-react#19]
Hi,
    I am using react + meteor, the code works well on local environment but when I move it to production (Heroku) all breaks and here is the error,

![file_stack_error](https://user-images.githubusercontent.com/5028648/26897105-b2474998-4be0-11e7-8d74-5af1db6b359a.png)

Any help will be appreciated. I tried the https://github.com/babel/babili with Heroku but does not work.

**Comment by cogKnitter** [comment]
Hello Muaaz.
I believe you have opened a ticket with Filestack as well. 
We think the issue with production may be that you are including both react-filestack as well as filestack-js in your build.

**Comment by muaaz-vf** [comment]
I have removed the file stack js as well but error persists 

Uncaught TypeError: r.emit is not a function
    at XMLHttpRequest.t.onreadystatechange (e437bb6….js?meteor_js_resource=true:36)

**Comment by muaaz-vf** [comment]
I have removed the file stack js as well but error persists 

Uncaught TypeError: r.emit is not a function
    at XMLHttpRequest.t.onreadystatechange (e437bb6….js?meteor_js_resource=true:36)

**Comment by lifeofjer** [comment]
Problem still exists - only when running **NODE_ENV production**: Removed `filestack-js` package - Only package installed is `react-filestack`.

See error below:

<img width="1680" alt="screen shot 2017-06-07 at 1 52 28 pm" src="https://user-images.githubusercontent.com/1686143/26900913-bb912b02-4b88-11e7-9ff4-90af23df7d03.png">

```
Uncaught TypeError: r.emit is not a function
    at XMLHttpRequest.t.onreadystatechange
```

**Comment by bmakuh** [comment]
I'm getting this as well. `filestack-js` is getting installed as a top-level dependency with Yarn. I even tried `import Filestack from 'filestack-react/dist/filestack-react'` to use your distribution version and the problem persists.

**Comment by bmakuh** [comment]
I figured it out: when you `import Filestack from 'filestack-react'` the file you end up importing is from `node_modules/filestack-react/dist`, which is a pre-minified file that includes React and everything else. If you try to minify this again with webpack (which you would be if you're bundling), it breaks.

**Comment by joshgeller** [comment]
@bmakuh Ben, what does the correct import path look like?

**Comment by bmakuh** [comment]
@joshgeller you'd need to import the source. I ended up just rolling my own component modeled after this one and using filestack-js directly.
