### ISSUE TITLE
How to transform an image and display it

### ISSUE THREAD

**Issue by randomdevpete** [filestack/filestack-react#25]
I think this is a documentation issue rather than functionality, but it is really not clear how I am supposed to transform an image (in my case a simple resize) and then display it. I would expect the ReactFilestack component in "transform" mode to do this. But the docs don't actually tell me even how to pass in the url or Filestack handle to be resized?

**Comment by samuxyz** [comment]
@chucksellick Hey sorry for the late reply. If I clearly understand you wanna resize the picture.
Within **filestack-react** you first need to pass the right `mode` prop equal to `'transform'`.

The official documentation https://www.filestack.com/docs/javascript-api/transform-v3 specifies the function requires two parameters, `url` and `options`.   To `ReactFilestack` they can be passed as a single object in the `options` prop:

```
const options = { url: 'PICTURE_URL', options: { resize: { width: 100 } } };
<ReactFilestack mode="transform" options={options} />
```

I think the confusion is that I did not create any `url` prop but instead send it as a property of a more general `options` object.

**Comment by sitch** [comment]
Would be nice if the react view exposed the `client` variable so that subsequent calls since the api isn't really well suited for single call compound image transforms.  I.e., if i want to guarantee PDF outputs, it looks like you must upload, transform, then upload again.  Let me know if this is not the case?

**Comment by samuxyz** [comment]
@Sitch If I clearly understand you would like access to the `client` api? That's possible, I could export it so you can import the component and the client this way:

```
import ReactFilestack, { client } from 'filestack-react';
```

Which is pretty much like having access to `filestack-js`. However, both the component `ReactFilestack` and `client` would need the API key when initialized. 

Does it reply to your suggestion?

**Comment by samuxyz** [comment]
@sitch v1.3.4 just push, `client` can be exported. If it's ok we can close this issue.
