### ISSUE TITLE
Docs broken

### ISSUE THREAD

**Issue by gthomas-appfolio** [filestack/filestack-react#26]
The links in Readme are not correct:
https://filestack.github.io gives a 404
and https://www.zerocho.com/portfolio/ReactFilestack gives a Cloudflare error

**Comment by samuxyz** [comment]
@gthomas-appfolio thanks for letting me know, I am gonna remove the first link. However I can access  https://www.zerocho.com/portfolio/ReactFilestack

**Comment by gthomas-appfolio** [comment]
Thanks, I can see it now, it must have been a server problem yesterday.
