### ISSUE TITLE
Granting unnecessary permissions to filestack

### ISSUE THREAD

**Issue by lucasfeliciano** [filestack/filestack-react#28]
I noticed that filestack asks for unnecessary permissions on services

![image](https://user-images.githubusercontent.com/968014/30634575-dc9091bc-9def-11e7-9f44-d37173f4b8d3.png)

As you can see it is asking for read, send, delete and manage emails.

Just read might be enough, don't it?

![image](https://user-images.githubusercontent.com/968014/30634838-b32f2d8c-9df0-11e7-9998-7c101d21d1b2.png)

Same thing goes to google drive.

I don't think this is related to filestack-react might be to filestack-js but since I'm using this package this is why I'm creating the issue here.

**Comment by cogKnitter** [comment]
Hello Lucas, 

I believe you have a ticket open with Filestack. We are looking into the delete option for gmail. In regard to Google Drive and similar services, we offer export of files to many services which is why read only access is not the default behavior.

**Comment by cogKnitter** [comment]
I'm going to close this issue since it pertains to the API and not to the React SDK.
