### ISSUE TITLE
How to use URL fromSource

### ISSUE THREAD

**Issue by jalembke** [filestack/filestack-react#29]
According to the filestack documentation for pick (https://www.filestack.com/docs/javascript-api/pick-v3), an app is allowed to use fromSources with the value of 'url' to allow a link to be used to upload a file.  It also says that this is the default.  However using the filestack react component 'url' is not turned on by default and when I attempt to use it in the fromSources option, I get an error with Unknown source 'url'.  Did some looking at the source code and found a reference to 'source-url' being a valid fromSource, however while that enabled the link menu on the left, it did not load any UI to allow a user to type a link.

Am I missing something here?

**Comment by jalembke** [comment]
Any update here?  I'm still a bit confused by the interface for how to do this.

**Comment by samuxyz** [comment]
@jalembke hey sorry for the late response.

So, I did actually checked myself and I found no problems. I tried to run one of the examples provided in `/examples/demo`, and in the UI I do have `url` as option.

I recorded my steps:
<img src="https://cdn.filestackcontent.com/8xaScDRR6uP8RRyEjoN7" />

It seems pretty fine to me, in case I misread anything let me know.
