### ISSUE TITLE
Update to use filestack-js 0.3?

### ISSUE THREAD

**Issue by neoromantic** [filestack/filestack-react#3]
Currently, react-filestack uses filestack-js 0.2.

Should it be updated to 0.3, no?

**Comment by ZeroCho** [comment]
@neoromantic okay I'll update it right now. Thank you for noticing me that

**Comment by neoromantic** [comment]
Cool! Thanks :)

**Comment by ZeroCho** [comment]
@neoromantic react-filestack@0.5.2 came out. Thanks again!
