### ISSUE TITLE
The widget takes much time to be shown

### ISSUE THREAD

**Issue by yhjor** [filestack/filestack-react#30]
The widget takes much time to be shown. However, there is only `onSuccess` and `onError` callback. How can we manage user's expectation like adding a spinner during the time to be shown? Or we can just let them wait for a few seconds to `cold start` the widget? For the native js API there is method like `onOpen`, but it is not implemented in this library.

**Comment by samuxyz** [comment]
@yhjor sorry for the late response.
If you are looking for functions like `onOpen`, `onFileUploadProgress` to have full control of the entire steps you just need to pass them in the `options` parameter.

For your reference, take a look at the official documentation example (https://www.filestack.com/docs/javascript-api/picker-examples-v3):

```
client.pick({
  uploadInBackground: false,
  hideWhenUploading: true,
  startUploadingWhenMaxFilesReached: true,
  onFileUploadProgress: function(file, progressEvent) {
    console.log(JSON.stringify(progressEvent.totalPercent))
  }
}).then(function(result) {
  console.log(JSON.stringify(result.filesUploaded))
})
```

**Comment by AndrzejSala** [comment]
@yhjor 
As wrote @samuxyz it can be done by passing specific properties to the options object.

More about possible picker options you can find in our docs:
https://filestack.github.io/filestack-js/interfaces/pickeroptions.html#onopen
