### ISSUE TITLE
Filestack client not exported as expected

### ISSUE THREAD

**Issue by smich** [filestack/filestack-react#32]
Hello! To begin with, thanks so much for writing this component! Up to now I was using a custom made component but after the intro of the v3 library I never found the time to update it.

As per the documentation, I tried to import the filestack client (`import { client } from 'filestack-react';`) but it was undefined. After a bit of digging I realized that it's not really exported. The `entry` point defined in `webpack.config.js` points to `./src/ReactFilestack` that exports only the `ReactFilestack` component. 

Can you please export the filestack client as per the documentation? I'm happy to raise a pr if you want.

Thanks,
/s

**Comment by samuxyz** [comment]
@smich sorry for the late reply.
Thank you for pointing it out, I was quite sure I did actually changed the entry point. I already pushed and published the small bug fix so you can upgrade the package.

Gonna close the issue.
