### ISSUE TITLE
Uncaught TypeError: n.emit is not a function   at XMLHttpRequest.t.onreadystatechange On AWS Server while locally working

### ISSUE THREAD

**Issue by tanweer-et** [filestack/filestack-react#35]
React v15.2.1 React Redux v4.4.5 

package.json

{
  "name": "abc",
  "version": "1.0.0",
  "description": "",
  "private": true,
  "engines": {
    "node": ">=6",
    "npm": ">=3"
  },
  "author": "Gigster",
  "scripts": {
    "analyze:clean": "rimraf stats.json",
    "preanalyze": "npm run analyze:clean",
    "analyze": "node ./internals/scripts/analyze.js",
    "npmcheckversion": "node ./internals/scripts/npmcheckversion.js",
    "preinstall": "npm run npmcheckversion",
    "postinstall": "npm run build:dll",
    "build": "cross-env NODE_ENV=production webpack --config internals/webpack/webpack.prod.babel.js --color -p || true",
    "build:clean": "npm run test:clean && rimraf ./build",
    "build:dll": "node ./internals/scripts/dependencies.js",
    "start": "cross-env NODE_ENV=development node server",
    "start:tunnel": "cross-env NODE_ENV=development ENABLE_TUNNEL=true node server",
    "start:production": "npm run build && npm run start:prod",
    "start:prod": "cross-env NODE_ENV=production node server",
    "pagespeed": "node ./internals/scripts/pagespeed.js",
    "presetup": "npm i chalk",
    "setup": "node ./internals/scripts/setup.js",
    "postsetup": "npm run build:dll",
    "clean": "shjs ./internals/scripts/clean.js",
    "clean:all": "npm run analyze:clean && npm run test:clean && npm run build:clean",
    "generate": "plop --plopfile internals/generators/index.js",
    "//": "THAT USED TO BE LINT npm run lint:js && npm run lint:css",
    "lint:eslint": "eslint --ignore-path .gitignore --ignore-pattern internals/scripts",
    "lint:js": "npm run lint:eslint -- . ",
    "lint:css": "stylelint ./app/**/*.css",
    "pretest": "npm run test:clean # && npm run lint",
    "test:clean": "#rimraf ./coverage",
    "test": "#cross-env NODE_ENV=test karma start internals/testing/karma.conf.js --single-run",
    "test:watch": "#npm run test -- --auto-watch --no-single-run",
    "test:firefox": "#npm run test -- --browsers Firefox",
    "test:safari": "#npm run test -- --browsers Safari",
    "test:ie": "#npm run test -- --browsers IE",
    "heroku-postbuild": "npm run build"
  },
  "babel": {
    "presets": [
      [
        "es2015",
        {
          "modules": false
        }
      ],
      "react",
      "stage-0"
    ],
    "env": {
      "production": {
        "only": [
          "app"
        ],
        "plugins": [
          "transform-react-remove-prop-types",
          "transform-react-constant-elements",
          "transform-react-inline-elements"
        ]
      }
    }
  },
  "eslintConfig": {
    "parser": "babel-eslint",
    "extends": "airbnb",
    "env": {
      "browser": true,
      "node": true,
      "mocha": true,
      "es6": true
    },
    "plugins": [
      "react",
      "jsx-a11y"
    ],
    "parserOptions": {
      "ecmaVersion": 6,
      "sourceType": "module",
      "ecmaFeatures": {
        "jsx": true
      }
    },
    "rules": {
      "import/no-unresolved": 2,
      "arrow-body-style": [
        2,
        "as-needed"
      ],
      "comma-dangle": [
        2,
        "always-multiline"
      ],
      "consistent-return": 0,
      "import/imports-first": 0,
      "import/newline-after-import": 0,
      "import/no-extraneous-dependencies": 0,
      "import/no-named-as-default": 0,
      "import/prefer-default-export": 0,
      "indent": [
        2,
        2,
        {
          "SwitchCase": 1
        }
      ],
      "react/jsx-space-before-closing": 0,
      "react/jsx-closing-bracket-location": [
        1,
        "after-props"
      ],
      "jsx-a11y/aria-props": 2,
      "jsx-a11y/heading-has-content": 0,
      "jsx-a11y/href-no-hash": 2,
      "jsx-a11y/label-has-for": 0,
      "jsx-a11y/mouse-events-have-key-events": 2,
      "jsx-a11y/no-static-element-interactions": 0,
      "jsx-a11y/role-has-required-aria-props": 2,
      "jsx-a11y/role-supports-aria-props": 2,
      "max-len": 0,
      "newline-per-chained-call": 0,
      "no-console": 1,
      "no-constant-condition": 0,
      "no-nested-ternary": 0,
      "no-return-assign": 0,
      "no-unused-expressions": 0,
      "no-use-before-define": 0,
      "prefer-template": 2,
      "react/forbid-prop-types": 0,
      "react/jsx-filename-extension": 0,
      "react/jsx-no-target-blank": 0,
      "react/no-unused-prop-types": 0,
      "react/require-extension": 0,
      "react/self-closing-comp": 0,
      "require-yield": 0
    },
    "settings": {
      "import/resolver": {
        "webpack": {
          "config": "./internals/webpack/webpack.test.babel.js"
        }
      }
    }
  },
  "stylelint": {
    "extends": "stylelint-config-standard",
    "rules": {
      "color-hex-case": "upper",
      "string-quotes": "single",
      "selector-pseudo-class-no-unknown": [
        true,
        {
          "ignorePseudoClasses": [
            "global"
          ]
        }
      ],
      "indentation": 2,
      "function-comma-space-after": "always-single-line",
      "rule-nested-empty-line-before": "never",
      "comment-empty-line-before": "never",
      "property-no-unknown": [
        true,
        {
          "ignoreProperties": [
            "composes"
          ]
        }
      ],
      "declaration-block-no-duplicate-properties": [
        true,
        {
          "ignore": [
            "consecutive-duplicates"
          ]
        }
      ]
    }
  },
  "dllPlugin": {
    "path": "node_modules/react-boilerplate-dlls",
    "exclude": [
      "chalk",
      "compression",
      "cross-env",
      "express",
      "ip",
      "minimist",
      "sanitize.css"
    ],
    "include": [
      "core-js",
      "lodash",
      "eventsource-polyfill"
    ]
  },
  "dependencies": {
    "axios": "0.13.1",
    "babel-polyfill": "6.13.0",
    "chalk": "1.1.3",
    "compression": "1.6.2",
    "copy-webpack-plugin": "^4.0.0",
    "cross-env": "^2.0.1",
    "crypto-js": "^3.1.8",
    "es6-docready": "^1.0.0",
    "es6-dom": "^1.0.0",
    "express": "4.14.0",
    "express-sslify": "^1.2.0",
    "extract-text-webpack-plugin": "^2.0.0-beta.4",
    "filestack-js": "^0.9.12",
    "filestack-react": "^1.3.8",
    "fontfaceobserver": "2.0.4",
    "history": "3.0.0",
    "html-webpack-plugin": "^2.22.0",
    "immutable": "3.8.1",
    "invariant": "2.2.1",
    "ip": "1.1.3",
    "lodash": "4.15.0",
    "minimist": "^1.2.0",
    "moment": "2.15.0",
    "offline-plugin": "^3.4.2",
    "postcss-cssnext": "^2.8.0",
    "postcss-nested": "^1.0.0",
    "postcss-reporter": "^1.4.1",
    "postcss-simple-vars": "^3.0.0",
    "react": "15.2.1",
    "react-addons-css-transition-group": "15.3.0",
    "react-addons-pure-render-mixin": "15.3.0",
    "react-autosuggest": "6.0.4",
    "react-datepicker": "0.29.0",
    "react-dd-menu": "1.0.7",
    "react-dom": "15.3.0",
    "react-dropzone": "3.6.0",
    "react-dropzone-component": "^2.0.0",
    "react-filepicker": "^0.10.16",
    "react-fontawesome": "^1.5.0",
    "react-ga": "^2.1.2",
    "react-helmet": "3.1.0",
    "react-https-redirect": "^1.0.9",
    "react-image-lightbox": "^4.3.0",
    "react-modal": "1.4.0",
    "react-month-picker": "^1.1.3",
    "react-phone-input": "1.1.3",
    "react-redux": "4.4.5",
    "react-router": "2.8.0",
    "react-router-redux": "4.0.5",
    "react-router-scroll": "0.3.2",
    "react-select": "1.0.0-rc.2",
    "react-slick": "0.12.2",
    "react-tooltip": "^3.3.0",
    "react-window-state": "0.1.3",
    "react-youtube-video": "^1.0.3",
    "redux": "3.6.0",
    "redux-form": "5.3.2",
    "redux-immutable": "3.0.8",
    "redux-saga": "0.11.1",
    "reselect": "2.5.3",
    "rimraf": "^2.5.4",
    "sanitize.css": "4.1.0",
    "spark-md5": "^3.0.0",
    "warning": "3.0.0",
    "webpack": "^2.1.0-beta.22",
    "whatwg-fetch": "1.0.0"
  },
  "devDependencies": {
    "babel-core": "6.14.0",
    "babel-eslint": "6.1.2",
    "babel-loader": "6.2.4",
    "babel-plugin-react-transform": "2.0.2",
    "babel-plugin-transform-react-constant-elements": "6.9.1",
    "babel-plugin-transform-react-inline-elements": "6.8.0",
    "babel-plugin-transform-react-remove-prop-types": "0.2.9",
    "babel-preset-es2015": "6.14.0",
    "babel-preset-react": "6.11.1",
    "babel-preset-react-hmre": "1.1.1",
    "babel-preset-stage-0": "6.5.0",
    "chai": "3.5.0",
    "chai-enzyme": "0.5.1",
    "cheerio": "0.22.0",
    "copy-webpack-plugin": "4.0.0",
    "css-loader": "0.25.0",
    "enzyme": "2.4.1",
    "eslint": "3.8.1",
    "eslint-config-airbnb": "11.1.0",
    "eslint-import-resolver-webpack": "0.5.1",
    "eslint-plugin-import": "1.14.0",
    "eslint-plugin-jsx-a11y": "2.2.2",
    "eslint-plugin-react": "6.2.0",
    "eventsource-polyfill": "0.9.6",
    "expect": "1.20.2",
    "expect-jsx": "2.6.0",
    "exports-loader": "0.6.3",
    "extract-text-webpack-plugin": "2.0.0-beta.4",
    "file-loader": "0.9.0",
    "html-loader": "0.4.3",
    "html-webpack-plugin": "2.22.0",
    "image-webpack-loader": "2.0.0",
    "imports-loader": "0.6.5",
    "json-loader": "0.5.4",
    "karma": "1.3.0",
    "karma-chrome-launcher": "1.0.1",
    "karma-coverage": "1.1.1",
    "karma-firefox-launcher": "1.0.0",
    "karma-ie-launcher": "1.0.0",
    "karma-mocha": "1.1.1",
    "karma-mocha-reporter": "2.1.0",
    "karma-safari-launcher": "1.0.0",
    "karma-sourcemap-loader": "0.3.7",
    "karma-webpack": "1.8.0",
    "lint-staged": "3.0.1",
    "minimist": "1.2.0",
    "mocha": "3.0.2",
    "ngrok": "^2.2.4",
    "null-loader": "0.1.1",
    "offline-plugin": "3.4.2",
    "plop": "1.5.0",
    "postcss-cssnext": "2.8.0",
    "postcss-loader": "0.13.0",
    "postcss-nested": "1.0.0",
    "postcss-reporter": "1.4.1",
    "postcss-simple-vars": "3.0.0",
    "psi": "2.0.4",
    "rimraf": "2.5.4",
    "shelljs": "0.7.4",
    "sinon": "2.0.0-pre",
    "style-loader": "0.13.1",
    "stylelint": "7.2.0",
    "stylelint-config-standard": "13.0.0",
    "url-loader": "0.5.7",
    "webpack": "2.1.0-beta.22",
    "webpack-dev-middleware": "1.7.0",
    "webpack-hot-middleware": "2.12.2"
  }
}

**Comment by samuxyz** [comment]
Could it be a problem with filestack-js itself?

**Comment by fmmoret** [comment]
Old but for anybody stuck on this: https://github.com/filestack/filestack-react/issues/19
You can configure your build system to avoid minification until your final bundling step
