### ISSUE TITLE
[BUG] Image bound expands by itself when cropping

### ISSUE THREAD

**Issue by marano** [filestack/filestack-react#36]
# Version
1.3.5

# How to reproduce it
1 - Open picker
2 - Select photo
3 - Reduce both sides of the photo crop area
4 - Click at one corner of the crop area and expand it to match the photo limit

# What happens
The opposite side bounds expand a little bit each time. But the faster the movement the more it expands.

# Expected behaviour
Only the side I am dragging should have its bounds resized

# Video
![bug](https://user-images.githubusercontent.com/52855/33271475-80b3472c-d36e-11e7-9188-27071585979b.gif)

**Comment by samuxyz** [comment]
Hey @marano it seems to me the problem is due to to filestack-js itself, have you tried to post the issue [there](https://github.com/filestack/filestack-js/issues)?

**Comment by marano** [comment]
Thank you @samuxyz! I opened an issue there at https://github.com/filestack/filestack-js/issues/71 and will close this.
