### ISSUE TITLE
Cannot read property 'resolvePromise' of undefined

### ISSUE THREAD

**Issue by erohin** [filestack/filestack-react#37]
I'm getting this error in filestask-js 0.9.12 and filestack-react 1.3.8
![image](https://user-images.githubusercontent.com/2608959/33712918-311ff3ec-db5a-11e7-8c49-3529af0eda6a.png)
Any thoughts?

**Comment by samuxyz** [comment]
have you tried to post the issue in filestack-js?

**Comment by erohin** [comment]
https://github.com/filestack/filestack-js/issues/76
