### ISSUE TITLE
Module build failed: ReferenceError: Unknown plugin "transform-class-properties" specified in ".../filestack-react/.babelrc"

### ISSUE THREAD

**Issue by adamchenwei** [filestack/filestack-react#38]
![screen shot 2018-01-02 at 3 02 03 pm](https://user-images.githubusercontent.com/4201698/34498097-07d188ba-efce-11e7-856c-81d3e44ea758.png)

Even after ( did `npm install babel-plugin-transform-class-properties --save` or use `yarn`. Why is that?

**Comment by adamchenwei** [comment]
I try to build the file-stack-react itself, btw

**Comment by jafetmorales** [comment]
Have you solved this problem?

**Comment by adamchenwei** [comment]
nop, just built my own version, this whole library is not that hard to just recreate a simpler version, customized as you see fit and build custom version when official one can't meet the requirement or having an issue 👍

**Comment by jafetmorales** [comment]
Turns out I did not need the library. Thank you anyways.
