### ISSUE TITLE
Where the client dom got attached to the react dom?

### ISSUE THREAD

**Issue by adamchenwei** [filestack/filestack-react#39]
I read the whole source code for `src/ReactFilestack.jsx` but I can't find the part where filestack attach itself to the dom.. somehow it just magically .. did.

if possible you can point me to the line that the dom attachment happens?https://github.com/filestack/filestack-react/blob/master/src/ReactFilestack.jsx

Thanks!

**Comment by AndrzejSala** [comment]
It's handled by filestack-js lib and inside ReactFilestack.jsx it's triggered by 
`client.picker({ ...options, onUploadDone: resolve }).open();`
