### ISSUE TITLE
No support for exposeOriginalFile

### ISSUE THREAD

**Issue by jarredkenny** [filestack/filestack-react#40]
It appears that `filestack-react` does not support the `exposeOrginalFile` option, however `filestack-js` does (in older versions, see below). 

After inspecting the source of the ReactFileStack component, it simply appears to passing the `options` object into the `filestack-js` client,  however the following error is thrown when using this option with the ReactFileStack component. 

```
Error: Unknown config option "exposeOriginalFile"
    at upload_queue.js:289
    at Array.forEach (<anonymous>)
    at e (upload_queue.js:285)
    at upload_queue.js:366
    at filestack-react.js:6
    at <anonymous>
```

As `filestack-react` appears to be a simple react component wrapping `filestack-js`, which is then a simple wrapper for the `api-client` package hosted on the FileStack servers, should this not be working?

I've confirmed this behaviour in a very simple [react application here](https://github.com/jarredkenny/filestack-react-test)

In the same repo you will find `non-react-test.html` which demonstrates the option working when using the library directly from the FileStack website. 

I was however able to use the `exposeOriginalFile` option in a react application without using the FIle Stack provided react components, but instead installed `filestack-js` and used the client that way. To do this, I had to install version 0.9.7 specifically, which appears to be the version in which the `exposeOriginalFile` option was implemented.

**Comment by AndrzejSala** [comment]
@jarredkenny I have tested it with the newest version of filestack-react (2.0.0) and filestack-js (1.14.1)  and it looks like the problem no more occurs.
