### ISSUE TITLE
Feature Request: Custom Designed button > Allow buttonText to accept JSX

### ISSUE THREAD

**Issue by natenrb9** [filestack/filestack-react#44]
Feature Request: Custom Designed button > Allow buttonText to accept JSX

This actually works to do what I want, I am passing JSX for an icon and text, and it does render the button correctly (with some CSS help), but it would be nice if it didn't throw an error...looks like it is just a matter of changing the prop type to accept an ob<ReactFilestack
          apikey={apiKey}
          buttonText={<span><AddCircle className={`${classes.addCircleIcon} ${classes.addCircleIconLibraryContent}`} />Add Content to Library</span>}
          buttonClass={`${classes.addButton} ${classes.addButtonLibraryContent}`}
          options={options}
          onSuccess={this.uploadSuccess}ject?

```
<ReactFilestack
   apikey={apiKey}
   buttonText={<span><AddCircle className={`${classes.addCircleIcon} ${classes.addCircleIconLibraryContent}`} />Add Content to Library</span>}
   buttonClass={`${classes.addButton} ${classes.addButtonLibraryContent}`}
   options={options}
   onSuccess={this.uploadSuccess}
/>
```

![screen shot 2018-03-21 at 3 30 49 pm](https://user-images.githubusercontent.com/9954488/37738542-f05e0532-2d1c-11e8-827d-44b6cc50cb01.png)

**Comment by samuxyz** [comment]
@natenrb9 Sorry for the super late reply, would you mind creating a PR for this yourself?

**Comment by natenrb9** [comment]
Just figured out I can use the Custom Render -> render prop for this, should have realized this before. Thanks.
