### ISSUE TITLE
npm archive

### ISSUE THREAD

**Issue by samuxyz** [filestack/filestack-react#6]
Hey @ZeroCho I was wondering if you could publish on npm again as the documentation is still for the 0.5.3 version. Now it's 0.6.4.

**Comment by ZeroCho** [comment]
@samuxyz Done!

**Comment by samuxyz** [comment]
@ZeroCho thanks for the fast reply!

**Comment by samuxyz** [comment]
btw, @ZeroCho is there any chance I can get listed in the collaborators list in npm?

**Comment by ZeroCho** [comment]
@samuxyz what's your npm account name?

**Comment by samuxyz** [comment]
@ZeroCho samuxyz, I have just created it.

**Comment by ZeroCho** [comment]
@samuxyz I added you. Check it!

**Comment by samuxyz** [comment]
@ZeroCho thanks a lot. Next, I will add some tests to the package.
