### ISSUE TITLE
Is there a way to show the dropPane without the pick button?

### ISSUE THREAD

**Issue by trufa** [filestack/filestack-react#61]
When I choose the web option for the dropPane then the dropPane is showed without any button. With react I only seem to be able to do it with a click on the button first. Is there any way around this?

Thanks!

**Comment by AndrzejSala** [comment]
@trufa 
Now, the component create `<button>` or `<a>` element and picker.open() is invoked when click on it.
We need to redefine logic of this component a little bit to made it possibly.

**Comment by trufa** [comment]
@AndrzejSala thanks for the answer! Is there any roadmap for that or is it not a planned feature?

**Comment by AndrzejSala** [comment]
@trufa 
I can't give you an exact date, but we are going to standardize all picker display modes to be useful in this react wrapper in May.

**Comment by AndrzejSala** [comment]
@trufa 
Happy to announce that yesterday we released a new version.

Get the newest and try this one:
```jsx
<ReactFilestack
  apikey={YOUR_API_KEY}
  action='pick'
  actionOptions={{
    displayMode: 'dropPane'
  }}
  container={HTML_NODE_ID}
  componentDisplayMode={{
    type: 'immediate'
  }}/>
```
