### ISSUE TITLE
PickerClose: Picker is already closed

### ISSUE THREAD

**Issue by IanVS** [filestack/filestack-react#77]
I'm rendering a filestack button inside a modal, and I notice that whenever I close the modal, even if I haven't opened up the filestack picker, I get a console warning of `PickerClose: Picker is already closed`.  Is there a way to avoid this?

**Comment by smdowl** [comment]
I also have this happening. I get it when I use:

```javascript
componentDisplayMode={{
  type: 'button',
}}
```

package works like a charm otherwise though :+1:

Oh, and I'm using React Router not a modal and experience the same issue.
