### ISSUE TITLE
Upload fails with large files on iPad and iPhone

### ISSUE THREAD

**Issue by crokadilekyle** [filestack/filestack-react#79]
When I try to upload larger files (the one in question is 1.29 GB) on iPad or iPhone 7 the upload quits part of the way through and the following errors show up in the console.

![Screen Shot 2020-02-08 at 9 45 23 PM](https://user-images.githubusercontent.com/47466333/74095263-652d5c00-4abc-11ea-9a80-f7fa9e1bfacc.png)

I had this issue in both Safari and Chrome on the iPad and Safari and Edge (the new edge) on the iPhone.  In Safari on my Mac Mini it almost was successful but failed right at the end (it had uploaded about 1150mb before failing).

I was able to successfully upload this file on PC.  I have also be able to successfully upload smaller files on iPad, iPhone and Safari on Mac.

**Comment by pcholuj** [comment]
This problem should be fixed now
