### ISSUE TITLE
Setting or Suppressing script tag version

### ISSUE THREAD

**Issue by JoshReedSchramm** [filestack/filestack-react#81]
We're including this component into a larger application that mixes React with more traditional client/server style web functionality - as opposed to a SPA. 

That means on a few pages we have this component as well as a non-react based implementation of filestack which is being included in the server-side rendered HTML. 

We're seeing a version conflict between the script tag that is automatically injected wither by this tool or by filestack-js itself when using the ES module include. 

Is there a way to specify which version of the filestack JS should be included or suppress inclusion of the script tag entirely so that it falls back to using the version we've included in the head of our rendered page?

**Comment by MowiliMi** [comment]
Can you paste sample code with error message?
