### ISSUE TITLE
Multiple Image selection

### ISSUE THREAD

**Issue by Harshit5295** [filestack/filestack-react#84]
const options = {
  accept: "image/*",
  maxFiles: 10,
  storeTo: {
    ocation: "s3"
  }
};

In the above I have mentioned maxFiles : 10
Still it is not allowing me to pick more than one image.

Here is my Modal Config:
<ReactFilestack
    apikey={"MY_API_KEY"}
    buttonText="Change"
    buttonClass="change_image"
    mode="pick"
    options={options}
    onSuccess={this.updateImage}
/>

**Comment by carmouche** [comment]
Hi there!  I was able to get mine working by passing my picker options to the `actionOptions` prop
```
const options = {
       displayMode: 'inline',
       container: 'embedded',
       maxFiles: 100
}


<ReactFilestack
      actionOptions={options}
/>
```
