### ISSUE TITLE
local uploads to ca-central-1 fail

### ISSUE THREAD

**Issue by jwreeder** [filestack/filestack-react#87]
Within one of our components we are using filestack-react v.3.1.0 (from package-lock.json). The version of picker that is fetched is 1.11.0. From within an environment that is using AWS ca-central-1. If an upload from the local file system is attempted it fails with the error "Invalid store upload params". If an upload from Dropbox is specified the upload succeeds. The error returned is from failed validation on the AWS region. There is a list of regions that are configured within filestack that the target region is checked against. The uploads work fine from other regions with v.3.1.0 and also in CA from components that are using v.2.0.6 (picker v.1.4.4). This may very well be an issue with the underlying filestack.js dep. If so please advise, also if this has been addressed in a newer version of filestack-react.
EDIT: Just wanted to add that no outbound network requests are made for local uploads, the error is thrown as part of local validation of the configuration. This validation appears to be performed server side for non-local uploads.
UPDATE: We changed the version to 2.0.6 and updated some param names for the component and it works so the issue is definitely with at least the referenced version above (3.1.0)
Thanks.

**Comment by jwreeder** [comment]
After some digging it appears that filestack-react is WAY behind the current version of filestack-js. The filestack-js version that filestack-react is pinned to (3.2.0) validates the AWS region against an array of hard-coded values which does not include ca-central-1. This is the case until filestack-js v.3.12.0 when the validation was changed to a regex pattern match. Is a fix to update the filestack-js dep in filestack-react in the pipeline and if so, when can it be expected?

**Comment by MowiliMi** [comment]
Hi folks, we test it and issue will be fixed after new release.

**Comment by jakubpeksa** [comment]
fixed with newest release 4.0
