### ISSUE TITLE
Some file types are not reporting mime types

### ISSUE THREAD

**Issue by ajaimesv** [filestack/filestack-react#88]
Hello,

We have been running tests with the latest version of the component and found that some file types are not reporting a mime type. For example, when uploading an mp4 file we get:

```json
"fileBlob": {
    "filename": "test.mp4",
    "handle": "handleId",
    "mimetype": "video/mp4",
    "originalPath": "test.mp4",
    "size": 1905864,
    "source": "local_file_system",
    "url": "https://domain.com/handleId",
    "uploadId": "uploadId",
    "originalFile": {
        "name": "test.mp4",
        "type": "video/mp4",
        "size": 1905864
    },
    "status": "Stored",
    "key": "keyId_test.mp4",
    "container": "containerId"
}
```

While we get this one with an mkv file:

```json
"fileBlob": {
    "filename": "test.mkv",
    "handle": "handleId",
    "originalPath": "/test.mkv",
    "size": 821777,
    "source": "local_file_system",
    "url": "https://domain.com/handleId",
    "uploadId": "uploadId",
    "originalFile": {
        "name": "test.mkv",
        "type": "",
        "size": 821777
    },
    "status": "Stored",
    "key": "keyId_ test.mkv",
    "container": "containerId"
}
```

As shown on the second example, the `mimetype` field is missing and the `type` field value is empty. The component is configured to accept both `.mp4` and `.mkv` file types. We have found this behavior happens with `.vtt` and `.mkv` file extensions, but there may be others.

This behavior seems to be consistent on all 3.x versions. Versions 2.x work as expected.

Thanks

**Comment by jakubpeksa** [comment]
Please report that issue in core lib https://github.com/filestack/filestack-js
