### ISSUE TITLE
How do I restrict file types accepted e.g. 'accept=image/*'?

### ISSUE THREAD

**Issue by tonyjmartinez** [filestack/filestack-react#97]
How do I limit the accepted file types like the 'accept' property [here](https://filestack.github.io/filestack-js/interfaces/pickeroptions.html#accept)?

**Comment by mpoisot** [comment]
Set it on the `actionOptions` property. ActionOptions is passed down to the filestack-js library. See all the allowed settings [here](https://filestack.github.io/filestack-js/interfaces/pickeroptions.html). 

```javascript
<FilestackReact
  apikey="..."
  action="pick"
  actionOptions={{
    accept: "image/*",
    allowManualRetry: true,
    fromSources: ["local_file_system"],
    transformations: {
      circle: false,
      crop: {
        aspectRatio,
        force: true,
      },
    },
  }}
/>
```
