### ISSUE TITLE
Can select file programmically? So go to `Edit image` directly?

### ISSUE THREAD

**Issue by myoneflag** [filestack/filestack-react#99]
I am uploading images by using filestack-react.
Once uploaded image, I'd like to edit the image again over filestack-editor without selecting the image.
How to use prop "file"? And any solution for directly editing image?
I checked filestack api doc and tried with createFile, getFile, onFileSelected. but not found a solution.
Please help me. 
Best regards

**Comment by jakubpeksa** [comment]
That looks like filestack-js question - please ask it there https://github.com/filestack/filestack-js
